### PR TITLE
Added ownership argument to synchronization/accumulation calls

### PR DESCRIPTION
**Pull request by cwsmith**
cleaned up version of PR #15

### CODE REVIEW

**Comment by atruszkowska** [comment]
Tested the changes today with the serial solver, all works well.

**Comment by cwsmith** [comment]
@tobinw Are there any other MSI tests to run before merging this?

**Comment by wrtobin** [comment]
@cwsmith Not at the present. MSI is only being used for xgc currently so far as I'm aware, while m3dc1 contains the code on which MSI was based but does not depend on MSI itself. So long as everything that is required for xgc is working I'm fine merging this (especially to fusion) for now.

We need to develop some additional test cases, but my current priority is some m3dc1 work after which I will be adding MSI as a dependency to m3dc1 and incorporating the work I've been doing on m3dc1 and LAS into MSI more directly. During that process I will be adding to the testing suite.

**Comment by cwsmith** [comment]
@tobinw OK.  Thank you.

**Pull request merged**
